VU Skills for AI 2021, W2 Blurring exercises

# Import statements

In [1]:
import numpy as np

# Applying a blur

A basic 6x6 blurring matrix looks as follows

In [2]:
M = np.array([[0.8,0.2,0,0,0,0], [0.2,0.6,0.2,0,0,0], [0,0.2,0.6,0.2,0,0],[0,0,0.2,0.6,0.2,0],[0,0,0,0.2,0.6,0.2],[0,0,0,0,0.2,0.8]])
print(M)

[[0.8 0.2 0.  0.  0.  0. ]
 [0.2 0.6 0.2 0.  0.  0. ]
 [0.  0.2 0.6 0.2 0.  0. ]
 [0.  0.  0.2 0.6 0.2 0. ]
 [0.  0.  0.  0.2 0.6 0.2]
 [0.  0.  0.  0.  0.2 0.8]]


We could, for example, apply the blurring matrix to a 6-dimensional vector v:

In [3]:
v = np.array([0.1,0.2,10,0.1,0.3,0.2])
print(v)

[ 0.1  0.2 10.   0.1  0.3  0.2]


This gives us

In [4]:
print(np.matmul(M,v))

[0.12 2.14 6.06 2.12 0.24 0.22]


Now, lets see how we can create our own blur matrices!

## Stronger blur

You can create a stronger blur by reapplying the blur to the same vector. 

In [5]:
print(v)
b = np.matmul(M,v)
print(b)
b2 = np.matmul(M,b)
print(b2)

[ 0.1  0.2 10.   0.1  0.3  0.2]
[0.12 2.14 6.06 2.12 0.24 0.22]
[0.524 2.52  4.488 2.532 0.612 0.224]


Since (A*B)*B is the same as A(B*B), you can also create a stronger filter and then apply it to the vector:

In [6]:
m2 = np.matmul(M,M)
print(m2)
print(np.matmul(m2,v))

[[0.68 0.28 0.04 0.   0.   0.  ]
 [0.28 0.44 0.24 0.04 0.   0.  ]
 [0.04 0.24 0.44 0.24 0.04 0.  ]
 [0.   0.04 0.24 0.44 0.24 0.04]
 [0.   0.   0.04 0.24 0.44 0.28]
 [0.   0.   0.   0.04 0.28 0.68]]
[0.524 2.52  4.488 2.532 0.612 0.224]


# Exercise

<b>Q1</b> <br>
Create a vector B of length 12 that represents the number of birthdays that you have in that month.

In [7]:
B = np.array([1,0,0,0,0,0,0,0,0,0,0,0])
print(B)

[1 0 0 0 0 0 0 0 0 0 0 0]


<b>Q2</b> <br>
Create a vector C of length 12 that represents the number of birthdays that your parents have in that month. <br>
(it must contain two 1’s or one 2 if they have their birthday in the same month)

In [26]:
C = np.array([0,0,0,0,1,0,0,0,0,0,0,1])
print(C)

[0 0 0 0 1 0 0 0 0 0 0 1]


<b>Q3</b> <br>
Blur vector B once. Print the result.

In [27]:
def create_matrix(size):  # first we need a function that creates empty matrices of the size we want (np.empty is not readable)
    if int(size) > 0:
        s = 1
        mat = []
        while s <= size:
            mat.append([0.0] * size) #the data type of matrix elements is set on creation, so float instead of int
            s += 1
        mat = np.array(mat)
    return mat


def create_blur_matrix(size):
    blurred_matrix = create_matrix(size)             # create a zeroes matrix of the required size
    if size > 1:
        for i in range(0, blurred_matrix.shape[1]):  # go through all columns of the matrix
            if i == 0:                               # set the edge case for the upper left corner
                blurred_matrix[i,i] = 0.8
                blurred_matrix[1,i] = 0.2
            elif i == (blurred_matrix.shape[1] - 1): # set the edge case for the bottom right corner
                blurred_matrix[i, i] = 0.8
                blurred_matrix[i-1, i] = 0.2
            else:
                blurred_matrix[i,i] = 0.6
                blurred_matrix[i-1,i] = 0.2
                blurred_matrix[i+1,i] = 0.2

        return blurred_matrix

M = create_blur_matrix(12)  #creation of blur matrix of size 12
B1 = np.matmul(M,B)  #Blurring vector B by multiplying it with blur matrix M and store it in B1.
print(B1)              


[0.8 0.2 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]


<b>Q4</b> <br>
Blur vector C once. Print the result. 

In [28]:
C1 = np.matmul(M,C)
print(C1)

[0.  0.  0.  0.2 0.6 0.2 0.  0.  0.  0.  0.2 0.8]


<b>Q5</b> <br>
Compute D = (B+C). Compute D2 by blurring D twice, print D2.

In [29]:
D = B + C
D1 = np.matmul(M,D)
D2 = np.matmul(M,D1)
print (D2)

[0.68 0.28 0.08 0.24 0.44 0.24 0.04 0.   0.   0.04 0.28 0.68]


<b>Q6</b> <br>
Compute B2 by blurring B twice. Compute C2 by blurring C twice. Compute BC2= B2 + C2. Print BC2.

In [30]:
B2 = np.matmul(M,B1)
C2 = np.matmul(M,C1)
BC2 = B2 + C2
print(BC2)

[0.68 0.28 0.08 0.24 0.44 0.24 0.04 0.   0.   0.04 0.28 0.68]


<b>Q7</b> <br>
Is BC2 always equal to D2? Find a counterexample, or provide an argument why these two must be equal.

In [32]:
#Example
X = np.array([0, 0, 3, 0, 5, 0, 0, 0, 0, 0, 0, 0]) 
Y = np.array([0, 0, 0, 4, 0, 0, 6, 0, 0, 0, 7, 0])
#addition of the vectors
Z = X + Y       
#Blurring the vectors
Z1 = np.matmul(M,Z)   
Z2 = np.matmul(M,Z1)  
print (Z2)
#Blurring the Vectors 
X1 = np.matmul(M,X)
Y1 = np.matmul(M,Y)
X2 = np.matmul(M,X1)
Y2 = np.matmul(M,Y1)
#Addition of the blurred vectors
XY2 = X2 + Y2
print(XY2)


[0.12 0.88 2.48 3.68 3.52 2.8  2.84 1.44 0.52 1.68 3.08 1.96]
[0.12 0.88 2.48 3.68 3.52 2.8  2.84 1.44 0.52 1.68 3.08 1.96]
